# Generated by Django 2.0 on 2018-01-25 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180124_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='opciones',
            name='pregunta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Preguntas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voto',
            name='id_opciones',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='voto',
            name='id_usuario',
            field=models.IntegerField(),
        ),
    ]
