# Generated by Django 2.0 on 2018-01-31 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180125_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='id_opciones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Opciones'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
